version: '3.4'

services:
  facesapi:
    image: ${DOCKER_REGISTRY-}facesapi
    build:
      context: .
      dockerfile: Faces/FacesApi/Dockerfile


  faces.webmvc:
    image: ${DOCKER_REGISTRY-}faceswebmvc
    build:
      context: .
      dockerfile: Faces.Web/Faces.WebMvc/Dockerfile
    depends_on:
      - sqldbservice
      - rabbitmq

  ordersapi:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Ordering/OrdersApi/Dockerfile
    depends_on:
      - sqldbservice
      - rabbitmq
      - facesapi

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: CustomerNotification/NotificationService/Dockerfile
    depends_on:
      - rabbitmq

  sqldbservice:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    container_name: sqlserver
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Passw00rd(!)
    ports:
     - "1403:1433"
     
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmqface
    ports:
      - "5672:5672"
      - "15672:15672"